<a href="https://colab.research.google.com/github/Diwash17/learning-pytorch/blob/main/pytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
print(torch.__version__)


2.5.0+cu121


In [4]:
print(torch.cuda.is_available())

True


In [5]:
lst=[[1,2,3],[4,5,6]]
tensor=torch.tensor(lst)

Tensor are building block of neural network and are similar as array

In [6]:
tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [7]:
tensor.type()

'torch.LongTensor'

Tensor can be created to shape as well

In [8]:
import numpy as np

In [9]:
np_array=np.array(lst)

In [10]:
np_tensor=torch.from_numpy(np_array)

In [11]:
np_tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

Tensor attributes

In [12]:
tensor.shape

torch.Size([2, 3])

In [13]:
tensor.dtype

torch.int64

In [14]:
tensor.device

device(type='cpu')

Operations in tensor

Most numpy array operation can be performed on pytorch tensor

creating our first neural network

In [15]:
import torch.nn as nn

In [16]:
input_tensor=torch.tensor([[0.3471, 0.4547, -0.2356]])

In [17]:
linear_layer=nn.Linear(
                       in_features=3,
                       out_features=2
)

In [18]:
output = linear_layer(input_tensor)
print(output)


tensor([[-0.5557,  0.5493]], grad_fn=<AddmmBackward0>)


In [19]:
linear_layer.weight

Parameter containing:
tensor([[ 0.3682, -0.4802,  0.3220],
        [ 0.5044,  0.1189, -0.0117]], requires_grad=True)

In [20]:
linear_layer.bias

Parameter containing:
tensor([-0.3893,  0.3174], requires_grad=True)